/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Robot_MPC_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[10] = {3, 3, 0, 2, 4, 4, 0, 1, 0, 1};
static const casadi_int casadi_s5[6] = {0, 3, 0, 0, 0, 0};

/* Robot_MPC_cost_ext_cost_e_fun_jac_hess:(i0[3],i1[],i2[],i3[13])->(o0,o1[3],o2[3x3,4nz],o3[],o4[0x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.;
  a1=8.;
  a2=arg[0]? arg[0][0] : 0;
  a1=(a1-a2);
  a3=casadi_sq(a1);
  a4=arg[0]? arg[0][1] : 0;
  a5=casadi_sq(a4);
  a3=(a3+a5);
  a5=256.;
  a3=(a3/a5);
  a3=(a0*a3);
  a5=1.0000000000000000e-03;
  a6=1.;
  a7=10.;
  a0=(a0-a2);
  a2=1.9000000000000001e+00;
  a0=(a0/a2);
  a8=casadi_sq(a0);
  a9=-2.9999999999999999e-01;
  a9=(a9-a4);
  a9=(a9/a2);
  a2=casadi_sq(a9);
  a8=(a8+a2);
  a2=1.6000000000000001e+00;
  a8=(a8-a2);
  a8=(a7*a8);
  a8=exp(a8);
  a6=(a6+a8);
  a5=(a5/a6);
  a3=(a3+a5);
  if (res[0]!=0) res[0][0]=a3;
  a3=5.2631578947368418e-01;
  a2=(a0+a0);
  a10=(a5/a6);
  a11=(a8*a10);
  a11=(a7*a11);
  a12=(a2*a11);
  a12=(a3*a12);
  a13=1.9531250000000000e-02;
  a1=(a1+a1);
  a1=(a13*a1);
  a12=(a12-a1);
  if (res[1]!=0) res[1][0]=a12;
  a12=(a9+a9);
  a1=(a12*a11);
  a1=(a3*a1);
  a4=(a4+a4);
  a13=(a13*a4);
  a1=(a1+a13);
  if (res[1]!=0) res[1][1]=a1;
  a1=0.;
  if (res[1]!=0) res[1][2]=a1;
  a1=-1.0526315789473684e+00;
  a13=(a1*a11);
  a4=-5.2631578947368418e-01;
  a0=(a0+a0);
  a0=(a4*a0);
  a0=(a7*a0);
  a0=(a8*a0);
  a14=(a10*a0);
  a5=(a5/a6);
  a15=(a5*a0);
  a15=(a15/a6);
  a16=(a10/a6);
  a0=(a16*a0);
  a15=(a15+a0);
  a15=(a8*a15);
  a14=(a14-a15);
  a14=(a7*a14);
  a14=(a2*a14);
  a13=(a13+a14);
  a13=(a3*a13);
  a14=3.9062500000000000e-02;
  a13=(a13+a14);
  if (res[2]!=0) res[2][0]=a13;
  a9=(a9+a9);
  a4=(a4*a9);
  a4=(a7*a4);
  a4=(a8*a4);
  a10=(a10*a4);
  a5=(a5*a4);
  a5=(a5/a6);
  a16=(a16*a4);
  a5=(a5+a16);
  a8=(a8*a5);
  a10=(a10-a8);
  a7=(a7*a10);
  a2=(a2*a7);
  a2=(a3*a2);
  if (res[2]!=0) res[2][1]=a2;
  if (res[2]!=0) res[2][2]=a2;
  a1=(a1*a11);
  a12=(a12*a7);
  a1=(a1+a12);
  a3=(a3*a1);
  a3=(a3+a14);
  if (res[2]!=0) res[2][3]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int Robot_MPC_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Robot_MPC_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Robot_MPC_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Robot_MPC_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Robot_MPC_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Robot_MPC_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Robot_MPC_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Robot_MPC_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Robot_MPC_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Robot_MPC_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Robot_MPC_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Robot_MPC_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Robot_MPC_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Robot_MPC_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Robot_MPC_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s4;
    case 3: return casadi_s1;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Robot_MPC_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Robot_MPC_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
